const mockRecipients = [
  {
    id: 1,
    name: "김하늘",
    backgroundColor: "rgba(220, 185, 255, 0.4)",
    backgroundImageURL: null,
    createdAt: "2023-11-01T10:00:00Z",
    messageCount: 3,
    recentMessages: [
      {
        id: 101,
        recipientId: 1,
        sender: "최지우",
        profileImageURL: "https://picsum.photos/200?random=1",
        relationship: "친구",
        content: "항상 고마워!",
        font: "Noto Sans",
        createdAt: "2023-11-01T10:10:00Z",
      },
      {
        id: 102,
        recipientId: 1,
        sender: "이수빈",
        profileImageURL: "https://picsum.photos/200?random=2",
        relationship: "지인",
        content: "화이팅!",
        font: "Pretendard",
        createdAt: "2023-11-01T10:11:00Z",
      },
      {
        id: 105,
        recipientId: 1,
        sender: "이수지",
        profileImageURL: "https://picsum.photos/200?random=3",
        relationship: "지인",
        content: "화이팅!",
        font: "Pretendard",
        createdAt: "2023-11-01T10:11:00Z",
      },
    ],
    reactionCount: 12,
    topReactions: [
      { id: 1, emoji: "👍", count: 20 },
      { id: 2, emoji: "❤️", count: 12 },
      { id: 3, emoji: "❤️", count: 7 },
    ],
  },
  {
    id: 2,
    name: "강영훈",
    backgroundColor: "rgba(255,211,130,0.7)",
    backgroundImageURL: null,
    createdAt: "2024-10-26T13:19:31Z",
    messageCount: 1,
    recentMessages: [
      {
        id: 103,
        recipientId: 2,
        sender: "김하은",
        profileImageURL: "https://picsum.photos/200?random=3",
        relationship: "가족",
        content: "열심히 일하는 모습 멋있습니다.",
        font: "Pretendard",
        createdAt: "2023-11-01T08:05:25Z",
      },
    ],
    reactionCount: 48,
    topReactions: [
      { id: 27, emoji: "😀", count: 14 },
      { id: 31, emoji: "🥹", count: 11 },
    ],
  },
  {
    id: 3,
    name: "이지은",
    backgroundColor: "#9DDDFF",
    backgroundImageURL: null,
    createdAt: "2023-11-03T09:00:00Z",
    messageCount: 3,
    recentMessages: [
      {
        id: 104,
        recipientId: 3,
        sender: "정우성",
        profileImageURL: "https://picsum.photos/200?random=4",
        relationship: "동료",
        content: "늘 존경합니다!",
        font: "나눔명조",
        createdAt: "2023-11-03T09:05:00Z",
      },
    ],
    reactionCount: 5,
    topReactions: [{ id: 33, emoji: "👏", count: 5 }],
  },
  {
    id: 4,
    name: "최우식",
    backgroundColor: "rgba(155, 226, 130, 0.3)",
    backgroundImageURL: null,
    createdAt: "2025-11-02T15:00:00Z",
    messageCount: 0,
    recentMessages: [],
    reactionCount: 0,
    topReactions: [],
  },
  {
    id: 5,
    name: "한지민",
    backgroundColor: "rgba(220, 185, 255, 0.4)",
    backgroundImageURL: null,
    createdAt: "2023-11-04T12:00:00Z",
    messageCount: 0,
    recentMessages: [],
    reactionCount: 3,
    topReactions: [{ id: 39, emoji: "💐", count: 3 }],
  },
  {
    id: 6,
    name: "박서준",
    backgroundColor: "rgba(155, 226, 130, 0.3)",
    backgroundImageURL: null,
    createdAt: "2023-11-05T13:00:00Z",
    messageCount: 0,
    recentMessages: [],
    reactionCount: 0,
    topReactions: [],
  },
];

export default mockRecipients;
